services:
  - type: web
    name: elastique-cold-traffic
    env: static
    staticPublishPath: ./cold-traffic
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=3600
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
